name: SonarCloud Code Analysis

on:
  push: 
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run tests with coverage
        run: mvn clean verify

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args: >
            -Dsonar.projectKey=angelodpadron_meli-apc-back
            -Dsonar.organization=angelodpadron
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
