name: SonarCloud Code Analysis

on:
  push: 
    branches: ["feature/*"]
  pull_request:
    branches: ["develop, master"]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args: >
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
